import type { Metadata } from 'next';
import styles from '../app/globals.module.scss';
import { CartProvider } from '../components/cart/cart';

export const metadata: Metadata = {
  title: 'Domains Marketplace',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <CartProvider>
      <html lang='en'>
        <body className={styles.whole}>{children}</body>
      </html>
    </CartProvider>
  );
}
