import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import styles from '../app/page.module.css';

export const metadata: Metadata = {
  title: 'Domains',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={styles.whole}>{children}</body>
    </html>
  );
}
